### ISSUE TITLE
text support

### ISSUE THREAD

**Issue by sewnie** [alpheratz0/apint#1]
first thing, dear THANK YOU for making this software, it can be so useful along with `xscreenshot` or another simple screenshot utility

also the title lol, i think this can easily be implemented with Freetype.

**Comment by alpheratz0** [comment]
Text, rectangle, rectangle fill, circle, ellipse, color picker, brushes, there's a lot of features I could implement, but I like to keep the code base relatively small, sorry :(

**Comment by alpheratz0** [comment]
Freetype was not easy when I tried, not great docs

**Comment by sewnie** [comment]
> Text, rectangle, rectangle fill, circle, ellipse, color picker, brushes, there's a lot of features I could implement, but I like to keep the code base relatively small, sorry :(

its alright, i thikn arrows by far would have been alot useful than text, thanks for your response!

**Comment by alpheratz0** [comment]
> > Text, rectangle, rectangle fill, circle, ellipse, color picker, brushes, there's a lot of features I could implement, but I like to keep the code base relatively small, sorry :(
> 
> its alright, i thikn arrows by far would have been alot useful than text, thanks for your response!

Just draw an arrow with the mouse jk, adding such a feature would require a big rewrite, because for now click=paint and it is easy to implement

**Comment by sewnie** [comment]
Xlib provides `XDrawString` call for drawing text, for XCB [they provide something else](https://xcb.freedesktop.org/tutorial/fonts/), and apparently the example usage is quite big... so i have to agree with you a little bit i suppose? time to use my tablet for doing text i suppose.

maybe for the example, used along with undo could do *something*.
