### ISSUE TITLE
zoom in or out or fullscreen feature

### ISSUE THREAD

**Issue by sewnie** [alpheratz0/apint#3]
yeah, zoom in or out and fullscreen can be used in conjunction with big images that dont fit the normal desktop or are as big as the screen basically.

with fullscreen it can be possible to draw ontop of the entire screen (with an image taken by `xscreenshot` like an screenshot program can!)

**Comment by alpheratz0** [comment]
You can move the image around holding the middle button down, I'll leave zoom in/out to feature-rich programs like gimp

**Comment by sewnie** [comment]
> I'll leave zoom in/out to feature-rich programs like gimp

Honestly at that point I'd just use gimp

Thanks for pointing the move mouse thing! Wasn't very clear in the manual.

**Comment by alpheratz0** [comment]
>Thanks for pointing the move mouse thing! Wasn't very clear in the manual.

Yeah controls was a missing section in the man page, fixed!!
